name: story_app_dicoding
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  http: ^1.2.1
  shimmer: ^3.0.0
  flutter_dotenv: ^5.1.0
  cherry_toast: ^1.11.0
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  font_awesome_flutter: ^10.7.0
  story_view: ^0.16.5

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
